---
name: Floorplan 3D
version: dev
slug: floorplan3d
description: 3D Floorplan viewer add-on that hosts a WebGL viewer made with Evergine
url: https://github.com/vicfergar/addon-floorplan3d
ingress: true
ingress_stream: true
panel_icon: mdi:floor-plan
init: false
homeassistant: 0.92.0b2
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8099/tcp: null
ports_description:
  8099/tcp: ASP.NET Web Application
hassio_api: true
hassio_role: homeassistant
homeassistant_api: true
auth_api: true
map:
  - ssl
options:
  ssl: false
schema:
  ssl: bool
